### ISSUE TITLE
flowers dataset splitting

### ISSUE THREAD

**Issue by guanchzh** [CupidJay/Training-Vision-Transformers-with-only-2040-images#2]
Hi, excuse me for a question. The offical flowers dataset have a mat file for data splitting and I found the train and val set size are both 1020, while the test set size is 6149. Do we use this split directly by combing the train and val set to size of 2040 to train and leaving the test set unchanged ? Thank you .

**Comment by CupidJay** [comment]
Yes, you are right. We combined the train and val set to the size of 2040.
