### ISSUE TITLE
Ask for help of Acc@1 in table 2 in the paper

### ISSUE THREAD

**Issue by guanchzh** [CupidJay/Training-Vision-Transformers-with-only-2040-images#3]
Hi, excuse me for a new question. I try to repeat the DINO acc@1 in table 2, but the results are very different from the paper. I use the code from facebookresearch/dino github repo. Could you share some special training setting ? I have noticed the training details in the end of the paper. Are the /tao parameter means the teacher temp ? And are there any other setting different from the offical repo ? Looking forward to your reply, thank you very much !

**Comment by CupidJay** [comment]
I can provide you with the code and script I used in my experiments. The code is available at [here](https://github.com/CupidJay/Training-Vision-Transformers-with-only-2040-images/tree/DINO-exp/DINO_exp).
