### ISSUE TITLE
where is the flowers dataset?

### ISSUE THREAD

**Issue by DeadWater1** [CupidJay/Training-Vision-Transformers-with-only-2040-images#4]

**Comment by CupidJay** [comment]
You can find the flowers dataset at this [website](https://www.robots.ox.ac.uk/~vgg/data/flowers/102/).

**Comment by DeadWater1** [comment]
> You can find the flowers dataset at this [website](https://www.robots.ox.ac.uk/~vgg/data/flowers/102/).
thanks
