### ISSUE TITLE
Experiments on cifar10/cifar100

### ISSUE THREAD

**Issue by haoranD** [CupidJay/Training-Vision-Transformers-with-only-2040-images#5]
Hi, 

Many thanks for your excellent work. I am truly interested in your work.

Did you try the cifar10 or cifar100? 

I also wonder if it is possible to do some experiments with ImageNet, but it seems that how to select/split the data is a big issue.

cheers.

**Comment by CupidJay** [comment]
Thanks for your interest. We have experimented on CIFAR10 and CIFAR100 (please refer to Table 4 in our [camera-ready](https://www.ecva.net/papers/eccv_2022/papers_ECCV/papers/136850218.pdf)). As for ImageNet, our code can be used on ImageNet without modification (only need to specify the dataset path and the total number of images). However, instance discrimination will encounter problems such as infrequent updating and high memory overhead for large-scale datasets, as analyzed in our paper.

**Comment by haoranD** [comment]
Many thanks for your detailed reply.
